spring.application.name=expensetracker


spring.datasource.url=jdbc:mysql://localhost:3306/expense
spring.datasource.username=root
spring.datasource.password=Tamil@123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.allow-circular-references=true

lm.studio.url=http://localhost:1234/v1/chat/completions
local.ai.url=http://localhost:5050/extract-image

expense.file.upload.path=/Users/tamilselvans/M.E/tamil/test-samples/
