from __future__ import annotations

import json
import re
from collections import OrderedDict
from typing import Any

from .normalization import normalize_amount, normalize_currency, normalize_date, normalize_text


HEADER_FIELDS = [
    "name",
    "invoice_number",
    "amount",
    "tax",
    "discount",
    "currency",
    "date",
    "due_date",
    "category",
    "comment",
    "seller_address",
    "client_name",
    "client_address",
    "payment_method",
    "bank_name",
    "account_number",
]
NUMERIC_FIELDS = {"amount", "tax", "discount"}
DATE_FIELDS = {"date", "due_date"}
ADDRESS_FIELDS = {"seller_address", "client_address"}
PROMPT_TEMPLATE = (
    "Extract invoice header fields from the OCR text and return strict JSON with these keys only:\n"
    "name, invoice_number, amount, tax, discount, currency, date, due_date, category, comment, "
    "seller_address, client_name, client_address, payment_method, bank_name, account_number\n\n"
    "OCR:\n"
    "{ocr_text}"
)


def build_header_prompt(ocr_text: str) -> str:
    return PROMPT_TEMPLATE.format(ocr_text=ocr_text.strip())


def header_only_payload(payload: dict[str, Any]) -> OrderedDict[str, Any]:
    header = OrderedDict()
    for field in HEADER_FIELDS:
        header[field] = payload.get(field)
    return header


def build_header_target(payload: dict[str, Any]) -> str:
    normalized = normalize_header_payload(payload, strict=False)
    return json.dumps(header_only_payload(normalized), ensure_ascii=True, separators=(",", ":"))


def normalize_header_payload(payload: dict[str, Any], strict: bool = True) -> OrderedDict[str, Any]:
    if not isinstance(payload, dict):
        raise ValueError("Header payload must be a JSON object.")

    extra_keys = set(payload) - set(HEADER_FIELDS)
    if strict and extra_keys:
        raise ValueError(f"Unexpected keys in header payload: {sorted(extra_keys)}")

    normalized = OrderedDict()
    for field in HEADER_FIELDS:
        value = payload.get(field)
        if field in NUMERIC_FIELDS:
            normalized[field] = normalize_amount(value)
        elif field in DATE_FIELDS:
            normalized[field] = normalize_date(value)
        elif field == "currency":
            normalized[field] = normalize_currency(value) if value not in (None, "") else None
        elif field in ADDRESS_FIELDS:
            normalized[field] = normalize_multiline_text(value)
        else:
            normalized[field] = normalize_text(value)

    if normalized["comment"] is None and normalized["invoice_number"] is not None:
        normalized["comment"] = f"Invoice {normalized['invoice_number']}"

    return normalized


def normalize_multiline_text(value: Any) -> str | None:
    text = normalize_text(value)
    if text is None:
        return None

    raw_lines = str(text).splitlines()
    if not raw_lines:
        collapsed = collapse_whitespace(text)
        return collapsed or None

    cleaned_lines = [collapse_whitespace(line) for line in raw_lines]
    cleaned_lines = [line for line in cleaned_lines if line]
    return "\n".join(cleaned_lines) if cleaned_lines else None


def collapse_whitespace(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value)).strip(" ,")


def extract_json_object(raw_text: str) -> str:
    text = raw_text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?", "", text).strip()
        text = re.sub(r"```$", "", text).strip()

    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        return text[start:end + 1]

    # Some seq2seq runs emit a JSON object body without the outer braces.
    fragment = text.strip().strip(",")
    if fragment.startswith('"') and ":" in fragment:
        return "{" + fragment + "}"

    if start < 0 or end <= start:
        raise ValueError("No JSON object found in model output.")
    return text[start:end + 1]


def parse_generated_header(raw_text: str) -> OrderedDict[str, Any]:
    json_text = extract_json_object(raw_text)
    try:
        payload = json.loads(json_text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON generated by model: {exc}") from exc
    return normalize_header_payload(payload, strict=True)
